packages:
  - .

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - vue-demi

verifyDepsBeforeRun: false

minimumReleaseAgeExclude:
  - '@takumi-rs/core-darwin-arm64@2.0.0-rc.16'
  - '@takumi-rs/core-darwin-x64@2.0.0-rc.16'
  - '@takumi-rs/core-linux-arm64-gnu@2.0.0-rc.16'
  - '@takumi-rs/core-linux-arm64-musl@2.0.0-rc.16'
  - '@takumi-rs/core-linux-x64-gnu@2.0.0-rc.16'
  - '@takumi-rs/core-linux-x64-musl@2.0.0-rc.16'
  - '@takumi-rs/core-win32-arm64-msvc@2.0.0-rc.16'
  - '@takumi-rs/core-win32-x64-msvc@2.0.0-rc.16'
  - '@takumi-rs/core@2.0.0-rc.16'
  - '@takumi-rs/helpers@2.0.0-rc.16'
  - '@types/node@26.1.1'
  - '@vue/language-core@3.3.7'
  - bare-path@3.1.1
  - brace-expansion@2.1.2
  - path-expression-matcher@1.6.2
  - vue-component-meta@3.3.7
  - vue-component-type-helpers@3.3.7
  - vue-tsc@3.3.7

allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  vue-demi: true
